/**
 * HYROX population distributions — real outcome data.
 *
 * Source: Kaggle dataset `jgug05/hyrox-results` (Seasons 4–6, ~92k finishers).
 * Ingested 2026-05-07 via `scripts/ingest-hyrox-results.mjs`.
 *
 * Format mapping:
 *   - `open` rows → `open_singles` (50,364 rows)
 *   - `pro` rows → `pro_singles` (11,458 rows)
 *   - `doubles` rows → `open_doubles` (28,046 rows)
 *   - `pro_doubles` not in the dataset; tables are empty and the predictor
 *     falls back to the synthesised distributions for that format.
 *   - `relay`, `elite`, `goruck` excluded (different formats).
 *
 * Sanity filters during ingestion:
 *   - total_time in [30 min, 5 h] (excludes DNS/scoring errors)
 *   - run_time in [20 min, 2.5 h]
 *
 * Refresh cadence: re-run the ingestion script per Kaggle dataset update,
 * paste the output back into this file, and bump `LAST_REFRESH_DATE`.
 */

type Format = 'open_singles' | 'pro_singles' | 'open_doubles' | 'pro_doubles';

/** True once real data has been ingested. While false, callers must fall back
 *  to synthesised distributions. */
export const POPULATION_DATA_AVAILABLE = true;

/** Date this file was last refreshed against the source dataset. */
export const LAST_REFRESH_DATE = '2026-05-07';

/** Last season(s) covered by the source dataset. */
export const LAST_VERIFIED_SEASON: string = 'S4–S6 (Kaggle jgug05/hyrox-results)';

/** Source identifier for telemetry / debug. */
export const POPULATION_DATA_SOURCE: 'kaggle' | 'hyroxresultapi' | 'scraped' | null = 'kaggle';

/**
 * Per-metric percentile breakpoint table per format.
 * Each entry: `[seconds, cumulativePercentile]` sorted ascending by seconds.
 * `cumulativePercentile` = "% of finishers slower than or equal to this time".
 */
// ── Generated by scripts/ingest-hyrox-results.mjs (89,868 rows) ─────────────
export const HYROX_TOTAL_PERCENTILE_TABLES: Record<Format, Array<[number, number]>> = {
  open_singles: [[3829, 1], [4163, 5], [4384, 10], [4793, 25], [5338, 50], [6042, 75], [6853, 90], [7448, 95], [8856, 99]],
  pro_singles:  [[3608, 1], [3893, 5], [4082, 10], [4469, 25], [4965, 50], [5561, 75], [6263, 90], [6770, 95], [7973, 99]],
  open_doubles: [[3402, 1], [3698, 5], [3890, 10], [4263, 25], [4747, 50], [5314, 75], [5959, 90], [6411, 95], [7412, 99]],
  pro_doubles:  [],
};

export const HYROX_RUN_PERCENTILE_TABLES: Record<Format, Array<[number, number]>> = {
  open_singles: [[1926, 1], [2101, 5], [2214, 10], [2425, 25], [2695, 50], [3034, 75], [3453, 90], [3786, 95], [4589, 99]],
  pro_singles:  [[1789, 1], [1903, 5], [1996, 10], [2168, 25], [2390, 50], [2647, 75], [2955, 90], [3186, 95], [3829, 99]],
  open_doubles: [[1919, 1], [2115, 5], [2237, 10], [2470, 25], [2762, 50], [3111, 75], [3524, 90], [3843, 95], [4540, 99]],
  pro_doubles:  [],
};

export const HYROX_STATIONS_PERCENTILE_TABLES: Record<Format, Array<[number, number]>> = {
  open_singles: [[1547, 1], [1695, 5], [1785, 10], [1961, 25], [2208, 50], [2533, 75], [2909, 90], [3201, 95], [3910, 99]],
  pro_singles:  [[1534, 1], [1680, 5], [1771, 10], [1965, 25], [2222, 50], [2534, 75], [2912, 90], [3227, 95], [3890, 99]],
  open_doubles: [[1173, 1], [1267, 5], [1322, 10], [1432, 25], [1577, 50], [1758, 75], [1961, 90], [2106, 95], [2425, 99]],
  pro_doubles:  [],
};

export const HYROX_ROXZONE_PERCENTILE_TABLES: Record<Format, Array<[number, number]>> = {
  open_singles: [[194, 1], [241, 5], [270, 10], [325, 25], [405, 50], [508, 75], [631, 90], [716, 95], [932, 99]],
  pro_singles:  [[156, 1], [194, 5], [218, 10], [259, 25], [323, 50], [406, 75], [502, 90], [580, 95], [766, 99]],
  open_doubles: [[178, 1], [219, 5], [247, 10], [303, 25], [380, 50], [477, 75], [587, 90], [662, 95], [837, 99]],
  pro_doubles:  [],
};

/**
 * Look up a percentile from a real distribution table. Returns null if no real
 * data exists for the given format — caller falls back to synthesised.
 *
 * Result is the cumulative percentile (% of finishers slower than or equal to
 * `timeSec`). Caller converts to "faster than X%" via `100 - result`.
 */
export function lookupRealPercentile(
  table: Record<Format, Array<[number, number]>>,
  format: Format,
  timeSec: number,
): number | null {
  const t = table[format];
  if (!t || t.length === 0) return null;
  // Linear interpolation between adjacent percentile points.
  if (timeSec <= t[0][0]) return t[0][1];
  if (timeSec >= t[t.length - 1][0]) return t[t.length - 1][1];
  for (let i = 1; i < t.length; i++) {
    const [t0, p0] = t[i - 1];
    const [t1, p1] = t[i];
    if (timeSec <= t1) {
      const frac = (timeSec - t0) / (t1 - t0);
      return Math.round(p0 + frac * (p1 - p0));
    }
  }
  return 100;
}
